@startwbs gambar-2-11-hierarki-prefab

skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 12
skinparam wbsDiagram {
  BackgroundColor #F5F5F5
  BorderColor #555555
  ArrowColor #3F3F3F
}

* Prefab Gedung
** Geometri Visual
*** Lantai 1
*** Lantai 2
*** Lantai berikutnya
** Material dan Tekstur
** Pointer
*** unity_object_name gedung
*** unity_object_name fasilitas 1
*** unity_object_name fasilitas berikutnya

@endwbs
