@startuml gambar-2-17-erd-inti-data-kampus

skinparam backgroundColor #FFFFFF
skinparam shadowing false
skinparam defaultFontName "Times New Roman"
skinparam defaultFontSize 11
skinparam ArrowColor #3F3F3F
skinparam entity {
  BackgroundColor #F5F5F5
  BorderColor #555555
}
hide circle
skinparam linetype ortho

entity "gedung" as gedung {
  * id : SERIAL <<PK>>
  --
  nama_gedung : VARCHAR <<UQ, NOT NULL>>
  deskripsi_gedung : TEXT
  lokasi : TEXT
  jumlah_lantai : INT
  foto_url : VARCHAR
  unity_object_name : TEXT <<UQ>>
}

entity "fasilitas" as fasilitas {
  * id : SERIAL <<PK>>
  --
  nama_fasilitas : VARCHAR <<NOT NULL>>
  deskripsi_fasilitas : TEXT
  tipe_fasilitas : VARCHAR
  color : VARCHAR
  lantai : INT
  foto_url : TEXT
  id_gedung : INT <<FK, NULLABLE>>
  unity_object_name : TEXT <<UQ>>
}

entity "fakultas" as fakultas {
  * id : SERIAL <<PK>>
  --
  nama_fakultas : VARCHAR <<UQ, NOT NULL>>
  deskripsi_fakultas : TEXT
  email : VARCHAR
  website : VARCHAR
  id_gedung_utama : INT <<FK, NULLABLE>>
}

entity "program_studi" as prodi {
  * id : SERIAL <<PK>>
  --
  nama_prodi : VARCHAR <<NOT NULL>>
  jenjang : VARCHAR <<NOT NULL>>
  id_fakultas : INT <<FK, NOT NULL>>
  akreditasi : VARCHAR
  (nama_prodi, jenjang, id_fakultas) <<UQ>>
}

gedung ||--o{ fasilitas : id_gedung / SET NULL
gedung ||--o{ fakultas : id_gedung_utama / SET NULL
fakultas ||--o{ prodi : id_fakultas / CASCADE

@enduml
